### ISSUE TITLE
Make npm package

### ISSUE THREAD

**Issue by datafast01** [BayBreezy/templates#1]
thanks for your efforts. It is working fine on local but when I try to use in my project it is not working. Can you please make npm package that we can use?
Thanks

**Comment by BayBreezy** [comment]
Hey @datafast01 ,

Thanks for reaching out. 
I would try to turn this into a package, the only issue is that I am not very confident in the dependencies for this package.

I would not want to create a package and then an unlayer update comes along that dismantles the whole thing.

If you chekc the repo where unlayer moved from vue 2 to vue 3, you will see where a lot of devs are having issues.

**Comment by datafast01** [comment]
Thanks for your reply,

I am working on my localhost. Can you please give me the environment variable names for the AWS S3 bucket?

**Comment by BayBreezy** [comment]
I am not sure I understand the question. I am not using AWS. 

Are you referring to the images that can be dropped into the editor? They are actually stored by the underlying package (Unlayer). Check the docs here for some more details 
https://docs.unlayer.com/docs/getting-started

**Comment by datafast01** [comment]
when I am uploading the image getting error from 

https://unlayer-assets-prod.s3.us-east-1.amazonaws.com/

**Comment by BayBreezy** [comment]
Yeah. That has something to do with the unlayer package itself. 

Some more details can be found here about uploads: https://docs.unlayer.com/docs/file-storage

**Comment by datafast01** [comment]
thanks, brother!

**Comment by BayBreezy** [comment]
YW! Let me know if anything else comes up!
